name: Release

on:
  release:
    types: [published]

jobs:
  psgallery_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Build Version
        run: |
          Write-Output "Run ID is $ENV:GITHUB_RUN_ID"
          Set-Location .\Office365MailAliases\
          (Get-Content Office365MailAliases.psd1 -Raw) -replace "<ReplaceWithBuildId>", $ENV:GITHUB_RUN_ID | Set-Content Office365MailAliases.psd1
        shell: pwsh

      - name: Publish to the PS Gallery
        run: |
          Publish-Module -Path '.\Office365MailAliases\' -NuGetApiKey ${{ secrets.PSGALLERY_API_KEY }}
        shell: pwsh
